version: "3.9"

services:
  scc-website:
    image: swiftlycoastalcode/scc-website
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/known/:/var/www/html/.well-known
    links:
      - "scc-website"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  dresspal-db:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=nico
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dresspal
    ports:
      - "5432:5432"
    volumes:
      - dress_pal:/var/lib/postgresql/data
      - ./src/main/resources/keys:/app/keys

  # DressPal
  dresspal-backend:
    image: itspetersen/dresspal-backend
    ports:
      - "8080:8080"
      - "8050:8050"
    depends_on:
      - "dresspal-db"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://dresspal-db:5432/dresspal"
      SPRING_DATASOURCE_USERNAME: nico
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_PASSWORD}
    volumes:
      - ./data/logs:/opt/app/logs
    links:
      - "dresspal-db"

  dresspal-frontend:
    image: itspetersen/dresspal-frontend
    ports:
      - "4000:4000"
    depends_on:
      - "dresspal-backend"
    environment:
      NODE_ENV: production

  dresspal-adminer:
    image: adminer
    restart: always
    depends_on:
      - "dresspal-db"
    ports:
      - "8081:8080"

volumes:
  dress_pal: