name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-dresspal-backend:
    name: Build Production Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Deploy new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: cd /home/${{ secrets.HOST_USERNAME }}/webservice && docker compose -f docker-compose-test.yml down && docker compose -f docker-compose-test.yml pull  && docker compose -f docker-compose-test.yml up db backend adminer frontend pg-client -d
